name: Build APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install Buildozer & Dependencies
      run: |
        sudo apt update
        sudo apt install -y python3 python3-pip python3-setuptools unzip openjdk-17-jdk
        pip install --upgrade pip
        pip install buildozer cython wheel

    - name: Install Android SDK & accept licenses
      run: |
        sudo mkdir -p /usr/lib/android-sdk
        cd /usr/lib/android-sdk
        wget https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip
        unzip commandlinetools-linux-11076708_latest.zip -d cmdline-tools
        sudo yes | sudo cmdline-tools/bin/sdkmanager --sdk_root=/usr/lib/android-sdk "platform-tools"
        sudo yes | sudo cmdline-tools/bin/sdkmanager --sdk_root=/usr/lib/android-sdk "build-tools;36.0.0"
        sudo yes | sudo cmdline-tools/bin/sdkmanager --licenses

    - name: Build APK
      run: |
        buildozer android debug

    - name: Upload APK
      uses: actions/upload-artifact@v2
      with:
        name: myapp
        path: bin/*.apk
